---
abstract: 'Access the Google Storage JSON API (currently experimental).'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
build_requires:
  Digest::MD5: 0
  File::Temp: 0
  Test::Class: 0
  Test::More: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-Storage
requires:
  HTTP::Status: 0
  JSON: 0
  LWP::MediaTypes: 0
  LWP::UserAgent: 6.04
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  URI::Escape: 3.29
  autodie: 0
  strict: 0
  warnings: 0
version: v0.1.0
